spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0.0"

loans:
  message: "Welcome to FakeBank loans related QA APIs "
  contactDetails:
    name: "Smith Ray - QA Lead"
    email: "smith@fakebank.com"
  onCallSupport:
    - (666) 555-1234
    - (666) 523-1345